"""Public interface for version-aware CF standardized region lookup."""

from .api import (
    get_catalog,
    get_dataset_info,
    get_region,
    get_region_names,
    get_region_shape,
    get_spatial_profile,
    list_cf_versions,
    list_hierarchy_edges,
    list_region_names,
    list_regions,
    list_spatial_profile_ids,
    list_spatial_profile_versions,
    list_spatial_profiles,
    match_regions,
)
from .catalog import CoordinatePair, RegionCatalog, resolve_coordinates
from .datasets import CFRegistry, CFRelease, SpatialProfileDataset
from .errors import (
    CFRegionsError,
    CFVersionNotFoundError,
    CoordinateError,
    GeometryResolutionNotFoundError,
    RegionDataError,
    RegionNotFoundError,
    SpatialProfileCompatibilityError,
    SpatialProfileNotFoundError,
)
from .models import (
    DatasetInfo,
    GeometryProcessing,
    GeometryRepresentation,
    HierarchyEdge,
    HierarchyEdgeOrigin,
    MappingReference,
    Region,
    RegionMatch,
    SourceReference,
    SpatialInterpretationProfile,
)
from .profiles import (
    DirectorySpatialProfileProvider,
    ResolvedSpatialProfile,
    SpatialProfileProvider,
    SpatialProfileResolver,
)

__all__ = [
    "CFRegionsError",
    "CFRegistry",
    "CFRelease",
    "CFVersionNotFoundError",
    "CoordinateError",
    "CoordinatePair",
    "DatasetInfo",
    "DirectorySpatialProfileProvider",
    "GeometryProcessing",
    "GeometryRepresentation",
    "GeometryResolutionNotFoundError",
    "HierarchyEdge",
    "HierarchyEdgeOrigin",
    "MappingReference",
    "Region",
    "RegionCatalog",
    "RegionDataError",
    "RegionMatch",
    "RegionNotFoundError",
    "ResolvedSpatialProfile",
    "SourceReference",
    "SpatialInterpretationProfile",
    "SpatialProfileCompatibilityError",
    "SpatialProfileDataset",
    "SpatialProfileNotFoundError",
    "SpatialProfileProvider",
    "SpatialProfileResolver",
    "get_catalog",
    "get_dataset_info",
    "get_region",
    "get_region_names",
    "get_region_shape",
    "get_spatial_profile",
    "list_cf_versions",
    "list_hierarchy_edges",
    "list_region_names",
    "list_regions",
    "list_spatial_profile_ids",
    "list_spatial_profile_versions",
    "list_spatial_profiles",
    "match_regions",
    "resolve_coordinates",
]

__version__ = "0.1.0"
